server:
  port: 9012
spring:
  profiles:
    active: product
#  resources:
#    static-locations: "${docs.path}/"
docs:
  dir: "${app.home}/docs/"
  file: index.html
  cache-seconds: 10

---
spring.thymeleaf.cache: off
spring.config.activate.on-profile: local
docs.cache-seconds: 0
---