server:
  port: 9012
spring:
  profiles:
    active: product
#  resources:
#    static-locations: "${docs.path}/"
docs:
  dir: "${app.home}/docs/"
  file: index.html
  cache-seconds: 60

---
spring:
  thymeleaf:
    cache: off
  config:
    activate:
      on-profile: local